### ISSUE TITLE
Cannot connect to filesystem on Mac

### ISSUE THREAD

**Issue by mmirza1** [modelcontextprotocol/servers#118]
**Describe the bug**
The Claude Mac client connects to the SQLite db but cannot connect to the file system. 

Here is what the json looks like:

{
  "mcpServers": {
    "sqlite": {
      "command": "uvx",
      "args": ["mcp-server-sqlite", "--db-path", "/Users/user/tech-stuff/testing-claude-mcp/test.db"]
    },
    "filesystem": {
      "command": "npx",
      "args": ["-y", "@modelcontextprotocol/server-filesystem", "/Users/user/folder-1"]
    }
  }
}

I know a similar  issue on Windows has been reported and closed. Does anyone have any issues with this on Mac or any suggestions how to solve this?

**Comment by mmirza1** [comment]
#121

**Comment by teamgroove** [comment]
> **Describe the bug** The Claude Mac client connects to the SQLite db but cannot connect to the file system.
> 
> Here is what the json looks like:
> 
> { "mcpServers": { "sqlite": { "command": "uvx", "args": ["mcp-server-sqlite", "--db-path", "/Users/user/tech-stuff/testing-claude-mcp/test.db"] }, "filesystem": { "command": "npx", "args": ["-y", "@modelcontextprotocol/server-filesystem", "/Users/user/folder-1"] } } }
> 
> I know a similar issue on Windows has been reported and closed. Does anyone have any issues with this on Mac or any suggestions how to solve this?

Is the name of your user really: user?

The bug around windows is, that it somehow doesn't work using: npx to instantly install and use the node-module to contrary installing ist with: "npm i -g @modelcontextprotocol/server-filesystem" and then using it by referncing the index.js file in the location it landed.

I dont know your system, but the prerequisite is having nodejs installed. if you have it installed you could use the same workaround as for windows and try that.

**Comment by mmirza1** [comment]
> > **Describe the bug** The Claude Mac client connects to the SQLite db but cannot connect to the file system.
> > Here is what the json looks like:
> > { "mcpServers": { "sqlite": { "command": "uvx", "args": ["mcp-server-sqlite", "--db-path", "/Users/user/tech-stuff/testing-claude-mcp/test.db"] }, "filesystem": { "command": "npx", "args": ["-y", "@modelcontextprotocol/server-filesystem", "/Users/user/folder-1"] } } }
> > I know a similar issue on Windows has been reported and closed. Does anyone have any issues with this on Mac or any suggestions how to solve this?
> 
> Is the name of your user really: user?
> 
> The bug around windows is, that it somehow doesn't work using: npx to instantly install and use the node-module to contrary installing ist with: "npm i -g @modelcontextprotocol/server-filesystem" and then using it by referncing the index.js file in the location it landed.
> 
> I dont know your system, but the prerequisite is having nodejs installed. if you have it installed you could use the same workaround as for windows and try that.

yes, npx was indeed the problem. the updated paths I added in response to the #121 work fine.

**Comment by TiansuYu** [comment]
I am having the same issue as well, using both the filesystem and github MCP sever, this is the conversation i had with the lastest claude-sonnet-3.5:

> Hi could you have a look at what folders i have under ~/Projects

> I apologize, but I don't have direct access to your local file system or ability to see what folders you have under ~/Projects. I can only interact with files and folders through GitHub using the provided API functions, or help you with information you directly share with me.
If you'd like to explore what's in your Projects directory, you'll need to:
>
> Look at it directly on your computer, or
Share the contents with me in our conversation
>
> Is there something specific you're trying to do with your Projects folder that I can help with?

This is the MCP server config I am using 
```json
{
    "mcpServers": {
      "filesystem": {
        "command": "npx",
        "args": ["-y", "@modelcontextprotocol/server-filesystem", "~/Projects/"]
      },
      "github": {
        "command": "npx",
        "args": ["-y", "@modelcontextprotocol/server-github"],
        "env": {
          "GITHUB_PERSONAL_ACCESS_TOKEN": "lalalala" (my token) 
        }
      }
    }
  }
```
I can verify that the github server works perfectly fine, i can fetch my private repos.
