### ISSUE TITLE
Community page not found

### ISSUE THREAD

**Issue by raiki61** [modelcontextprotocol/servers#120]
**Describe the bug**  
The following link in the https://github.com/modelcontextprotocol/servers/blob/main/CONTRIBUTING.md leads to a "404 Not Found" page:  
`https://github.com/modelcontextprotocol/servers/discussions`

**To Reproduce**  
1. Visit the link provided in the documentation.  

**Expected behavior**  
The link should direct to a valid page or discussion on GitHub.

**Logs**  
N/A  

**Additional context**  
Please verify the link and update it in the documentation to ensure proper navigation.

**Comment by dsp-ant** [comment]
Fixed in https://github.com/modelcontextprotocol/servers/commit/18f6ab6ce8650d2fedd42420db968965bb010f11
