### ISSUE TITLE
Different labels for issues on different servers?

### ISSUE THREAD

**Issue by LaurentAjdnik** [modelcontextprotocol/servers#126]
Hello.

In this repo, different servers are maintained by different contributors and used by different testers.

Would it make sense to have a label per server for declaring/filtering issues?

Currently, it is handled by mentions in the title or the body (when not forgotten at all).

Thanks!

**Comment by jspahrsummers** [comment]
Thanks, this is a good suggestion! I think with [the changes to narrow the scope of this repo](https://github.com/orgs/modelcontextprotocol/discussions/61), we might be OK, but we'll definitely consider this if the issue backlog gets out of control.
