### ISSUE TITLE
How to use this in linux ?

### ISSUE THREAD

**Issue by hemangjoshi37a** [modelcontextprotocol/servers#136]
How to use this in linux ?

Basically I dont have access to windows or mac, how can i use this MSP ?

**Comment by dsp-ant** [comment]
Closing this out. See https://github.com/modelcontextprotocol/python-sdk/issues/81. Please do not spam the repositories with multiple issue and/or commenting about the same issue. Feel free to open a discussion https://github.com/orgs/modelcontextprotocol/discussions

**Comment by hemangjoshi37a** [comment]
sorry for the inconvenience .
