### ISSUE TITLE
Puppeteer throws a error MCP error -32603: Attempted to use detached Frame 

### ISSUE THREAD

**Issue by psv2522** [modelcontextprotocol/servers#140]
**Describe the bug**
Puppeteer throws this error on Win 11. It worked when i first used the server but since then i get the same error
![image](https://github.com/user-attachments/assets/12c87ea6-daf9-4f46-899f-801f19c9f2a0)

**To Reproduce**
1. Configure puppeteer in Win11 and ask to navigate to websites. (Works fine for the first time).
2. Get the above error message if i close the puppeteer instance and start a new chat in claude.

**Expected behavior**
Launch instance and navigate as needed

**Logs**

MCP Logs
2024-11-30T08:46:22.787Z [info] Attempting to connect to MCP server puppeteer...
2024-11-30T08:46:22.816Z [info] Connected to MCP server puppeteer!

Chat logs 
Error executing code: MCP error -32603: Attempted to use detached Frame 'BDCD1535EEAFBBE29C081FDB654FC86E'.

**Additional context**

**Comment by cwille97** [comment]
I encountered this as well, on macOS 15.1.1. You can work around this by closing out of the Claude application completely, as well as the "Google Chrome for Testing" app that Claude launched through puppeteer. For me, this happens on Claude version 0.7.1, Chrome testing version is Version 131.0.6778.85 (Official Build) (arm64).

**Comment by jspahrsummers** [comment]
Thanks for flagging! Merging with https://github.com/modelcontextprotocol/servers/issues/53.
