### ISSUE TITLE
Bug in example servers (toolResult confusion)

### ISSUE THREAD

**Issue by Madd0g** [modelcontextprotocol/servers#151]
**Describe the bug**

it seems like a couple of servers are returning `content` within `toolResult`.

Visible in this search (puppeteer/google maps): https://github.com/search?q=repo%3Amodelcontextprotocol%2Fservers%20toolResult&type=code

From the MCP client typescript completions, I see that `content` should be NEXT TO `toolResult`, not inside it.

**Expected behavior**
It makes sense to me that content is the "chat response" and toolResult is arbitrary data that the tool returns, so content should never be inside the result. **Please tell me** if this is a wrong assumption (since we have no examples of full featured clients).

**Additional context**
I am playing with the client and trying to understand inputs/outputs, vscode with zod make it _really_ hard to see what's happening.

Since I played with created my own MCP, I can see why the bug can easily happen, this is what I get as autocomplete:

```ts
server.setRequestHandler(CallToolRequestSchema, async (request) => {

return {
// autocomplete list I get in vscode (all of these are `unknown`):
capabilities
completion
content
contents
messages
prompts
protocolVersion
resources
resourceTemplates
serverInfo
then
tools
_meta
description
isError
}
```

1. It seems to be like a bunch of these don't belong here
2. No `toolResult` as an option at all
3. Nothing has a type

From the client side, I just see these from callTool `{ content, isError, toolResult, _meta }`

Thanks! MCP is cool!

**Comment by Madd0g** [comment]
Cool, one more question - is `toolResult` an official thing still?

It would be really nice to keep it as an option, so some clients could do their own formatting decisions?

**Comment by dsp-ant** [comment]
If there is a need, it might be best to open an issue in the specification repo detailing the problem you are trying to solve and preferable a suggested solution. This way we might include it into the draft for the next revision.

**Comment by Madd0g** [comment]
I very much want it back, I was playing around with implementing a client and having JUST ONE arbitrary data field makes developing compatible (to each other) client+servers much more feasible while still using the `content` for chat-related feature of the tool call, while being able to pass ANYTHING in `toolResult`

**Comment by Madd0g** [comment]
also, honestly, doing the data formatting decision for both the client and the AI makes them less powerful, a "raw result" option just makes future stuff more composable?

**Comment by Madd0g** [comment]
thank you, I did open an issue, but while it is being resolved, I noticed another problem - 

The [docs site](https://modelcontextprotocol.io/docs/concepts/tools) shows the typescript example returning `toolResult` while the python returns the content array (not an object).

However in the error handling section, I see both typescript and python returning an object with isError (not just content array).
