### ISSUE TITLE
Github connection is not working

### ISSUE THREAD

**Issue by experienceswithanish** [modelcontextprotocol/servers#155]
I have tried connecting with Claude and Github using MCP for windows
I tried the first method given by the Anthropic but couldn't connect.

Now I have tried the second method using the following method and this Sql lite is connected but other servers are not getting connected.

"Step-by-Step Guide:
1. Locate Node.js and npm paths
Open Command Prompt (CMD) as administrator and run:

where node
This will show your Node.js executable path. Example output:

D:\Program\nvm\node.exe
Then find your global npm packages location:

npm root -g
Example output:

D:\Program\nvm\node_modules
2. Install Required Packages Globally
Run these commands in CMD:

npm install -g @modelcontextprotocol/server-filesystem
npm install -g @modelcontextprotocol/server-github
npm install -g @modelcontextprotocol/server-memory
npm install -g @modelcontextprotocol/server-puppeteer
npm install -g @modelcontextprotocol/server-brave-search
npm install -g @modelcontextprotocol/server-google-maps
npm install -g @modelcontextprotocol/server-postgres
3. Verify Installations
Check each package installation:

npm list -g @modelcontextprotocol/server-filesystem
npm list -g @modelcontextprotocol/server-github
npm list -g @modelcontextprotocol/server-memory
npm list -g @modelcontextprotocol/server-puppeteer
npm list -g @modelcontextprotocol/server-brave-search
npm list -g @modelcontextprotocol/server-google-maps
npm list -g @modelcontextprotocol/server-postgres
Expected output format:

D:\Program\nvm -> .\
`-- @modelcontextprotocol/server-[package-name]@0.5.1
4. Update Configuration File
Modify your claude_desktop_config.json with the following content (adjust paths according to your system):

{
  "mcpServers": {
    "sqlite": {
      "command": "uvx",
      "args": [
        "mcp-server-sqlite",
        "--db-path",
        "D:\\github_repository\\test.db"
      ]
    },
    "filesystem": {
      "command": "D:\\Program\\nvm\\node.exe",
      "args": [
        "D:\\Program\\nvm\\node_modules\\@modelcontextprotocol\\server-filesystem\\dist\\index.js",
        "D:\\github_repository",
        "D:\\github_repository\\image-generator"
      ]
    },
    "github": {
      "command": "D:\\Program\\nvm\\node.exe",
      "args": [
        "D:\\Program\\nvm\\node_modules\\@modelcontextprotocol\\server-github\\dist\\index.js"
      ],
      "env": {
        "GITHUB_PERSONAL_ACCESS_TOKEN": ""
      }
    },
    "postgres": {
      "command": "D:\\Program\\nvm\\node.exe",
      "args": [
        "D:\\Program\\nvm\\node_modules\\@modelcontextprotocol\\server-postgres\\dist\\index.js",
        "postgresql://localhost/mydb"
      ]
    },
    "memory": {
      "command": "D:\\Program\\nvm\\node.exe",
      "args": [
        "D:\\Program\\nvm\\node_modules\\@modelcontextprotocol\\server-memory\\dist\\index.js"
      ]
    },
    "puppeteer": {
      "command": "D:\\Program\\nvm\\node.exe",
      "args": [
        "D:\\Program\\nvm\\node_modules\\@modelcontextprotocol\\server-puppeteer\\dist\\index.js"
      ]
    },
    "brave-search": {
      "command": "D:\\Program\\nvm\\node.exe",
      "args": [
        "D:\\Program\\nvm\\node_modules\\@modelcontextprotocol\\server-brave-search\\dist\\index.js"
      ],
      "env": {
        "BRAVE_API_KEY": ""
      }
    },
    "google-maps": {
      "command": "D:\\Program\\nvm\\node.exe",
      "args": [
        "D:\\Program\\nvm\\node_modules\\@modelcontextprotocol\\server-google-maps\\dist\\index.js"
      ],
      "env": {
        "GOOGLE_MAPS_API_KEY": ""
      }
    },
    "fetch": {
      "command": "uvx",
      "args": [
        "mcp-server-fetch"
      ]
    }
  },
  "globalShortcut": "Ctrl+Q"
}
"

I have been trying it for more than 2 days but couldn't get it connected.

**Comment by hemangjoshi37a** [comment]
This is similar to my issue in #152 that is solved in #40

**Comment by experienceswithanish** [comment]
> This is similar to my issue in #152 that is solved in #40

I have just used your config file and it worked.
I don't know how to thank you, seriously I have been trying to get it worked for more than 3 days and finally got it
Thank you
