### ISSUE TITLE
Error : `Claude will return soon Claude.ai is currently experiencing a temporary service disruption. We’re working on it, please check back soon.`

### ISSUE THREAD

**Issue by hemangjoshi37a** [modelcontextprotocol/servers#170]
When i run this prompt : `create a empty file named test.txt in the test_mcp_git folder` 

I get this screen : 

![image](https://github.com/user-attachments/assets/33ac3472-5202-4d7c-95b5-24710edd1228)

However my daily quota is not finished . When I restart the claude app it starts working fine again until i run the given prompt.

also   here is my MCP config file for the reference : 

```json
{
  "mcpServers": {
    "git": {
      "command": "python3.11",
      "args": [
        "-m",
        "mcp_server_git",
        "--repository",
        "C:\\Users\\heman\\Desktop\\test_mcp_git"
      ]
    },
    "memory": {
      "command": "node",
      "args": [
        "C:\\Users\\heman\\AppData\\Roaming\\npm\\node_modules\\@modelcontextprotocol\\server-memory\\dist\\index.js"
      ]
    },
    "filesystem": {
      "command": "node",
      "args": [
        "C:\\Users\\heman\\AppData\\Roaming\\npm\\node_modules\\@modelcontextprotocol\\server-filesystem\\dist\\index.js",
        "C:\\Users\\heman\\Desktop",
        "C:\\Users\\heman\\Desktop\\test_mcp_git"
      ]
    },
    "github": {
      "command": "node",
      "args": [
        "C:\\Users\\heman\\AppData\\Roaming\\npm\\node_modules\\@modelcontextprotocol\\server-github\\dist\\index.js"
      ],
      "env": {
        "GITHUB_PERSONAL_ACCESS_TOKEN": "my-token"
      }
    }
  }
}
```

Here is the screenshot of normal chat after reloading the claude app after the above mentioned error : 

![image](https://github.com/user-attachments/assets/35f724e7-9162-4ba7-9afb-88129216eb1e)

**Comment by jspahrsummers** [comment]
This isn't related to the reference server implementations in this repository, so I'm going to close this out. If you continue to have issues, please contact https://support.anthropic.com.
