### ISSUE TITLE
Filesystem could use an edit_file capability

### ISSUE THREAD

**Issue by robotdad** [modelcontextprotocol/servers#183]
**Is your feature request related to a problem? Please describe.**
write_file is awesome, but it doesn't isn't trustworthy for existing files, especially when they are large or the response is just small targeted changes.

**Describe the solution you'd like**
I'd like to see an edit_file capability working on smaller portions of the file.

**Comment by dhodun** [comment]
Even a `str_replace` tool would be helpful here. Cuts down on output tokens as well.
