### ISSUE TITLE
Could not attach to MCP server sequential-thinking on Mac desktop app

### ISSUE THREAD

**Issue by th3f001** [modelcontextprotocol/servers#185]
**Describe the bug**
![2024-12-02_19-32](https://github.com/user-attachments/assets/229f322c-0254-42f9-bea9-1b83ba10c4d2)

However, under settings it shows up...

![image](https://github.com/user-attachments/assets/86b2d7e8-63e7-437b-af13-c47482bc95ea)

...in the mcp.log everything is reported to work fine...

![image](https://github.com/user-attachments/assets/b70cc036-f6fb-4548-9a5b-775365ae6284)

**To Reproduce**
1. Modify the calude_desktop_config.json as per Github instructions
2. Open Claude for Mac desktop app
3. Inspect the MCP tools available
4. the red pop-up will appear in top right corner after 1-2 secs

**Expected behavior**

**Logs**
As per pics

**Additional context**
There seems to be a problem in finding the package on the npm registry (maybe a package naming typo on one of the configuration files?)

![image](https://github.com/user-attachments/assets/4cf934c9-8f5e-4908-9eea-7933922eca78)

![image](https://github.com/user-attachments/assets/28038c96-31c8-4308-a2da-70fb5f50737d)

**Comment by dsp-ant** [comment]
Which Claude Desktop version are you using?

**Comment by jspahrsummers** [comment]
The package was actually not published yet, so that should be fixed now. Please make sure to reference it as `@modelcontextprotocol/server-sequential-thinking` (with the additional dash). Let us know if it still doesn't work!

**Comment by th3f001** [comment]
Huge THANKS! It now works perfectly!

![image](https://github.com/user-attachments/assets/90111ace-7b5a-42f4-9f74-0bba6d9cbf3f)
