### ISSUE TITLE
MCP gitlab is not working 

### ISSUE THREAD

**Issue by TheSPST** [modelcontextprotocol/servers#192]
gitlab is unable to connect via mcp server using mac os 

```
"mcpServers": {
        "gitlab": {
            "command": "npx",
            "args": ["-y", "@modelcontextprotocol/server-gitlab"],
            "env": {
                "GITLAB_PERSONAL_ACCESS_TOKEN": "-----",
                "GITLAB_URL": "----",
                "GITLAB_PROJECT_ID": "0-----0"
            }
        }
}
```
other npx server is working fine like filesystem, brevSearch etc

**Comment by TheSPST** [comment]
<img width="500" alt="Screenshot 2024-12-03 at 3 10 09 PM" src="https://github.com/user-attachments/assets/4d1d17bd-4d23-42b6-98be-70ca9daefd7c">
<img width="383" alt="Screenshot 2024-12-03 at 12 49 34 PM" src="https://github.com/user-attachments/assets/4b9c64f8-5e2f-4884-9b84-386a67d8a43a">

**Comment by jspahrsummers** [comment]
What do [the logs](https://modelcontextprotocol.io/docs/tools/debugging) say?

**Comment by dsp-ant** [comment]
This is now fixed. Sorry
