### ISSUE TITLE
@modelcontextprotocol/server-gitlab is not published

### ISSUE THREAD

**Issue by xtuc** [modelcontextprotocol/servers#225]
it looks like @modelcontextprotocol/server-gitlab is missing or is private on npm: https://npmjs.com/package/@modelcontextprotocol/server-gitlab.

https://github.com/modelcontextprotocol/servers/blob/df0b733c7d086432de14504863c9c0288fc36686/src/gitlab/package.json#L2

Could you please publish it?

**Comment by dsp-ant** [comment]
Thank you for reporting this. This is now fixed.
