### ISSUE TITLE
Issue: Brave Search MCP Server Fetch Error on Macos

### ISSUE THREAD

**Issue by katyjohn124** [modelcontextprotocol/servers#226]
![image](https://github.com/user-attachments/assets/130ace45-546c-4cda-9802-d78b656f8edd)

Environment

	•	Claude Desktop Version: maybe latest version
	•	Brave Search MCP Server Version: ["0.5.2"]
	•	Node.js Version: [v22.11.0]
	•	npx Version: [10.9.0]

location:CN mainland

Description of the Issue

After configuring the Brave Search MCP Server in Claude Desktop, I encountered an error while attempting to perform a web search. Here’s the setup and the issue:
	1.	The Brave Search MCP Server is properly added to claude_desktop_config.json as per the documentation:

{
  "mcpServers": {
    "brave-search": {
      "command": "npx",
      "args": [
        "-y",
        "@modelcontextprotocol/server-brave-search"
      ],
      "env": {
        "BRAVE_API_KEY": "YOUR_API_KEY_HERE"
      }
    }
  }
}

	2.	Logs indicate that the Brave Search MCP Server is successfully running and connected:

2024-12-04T14:48:08.913Z [info] Connected to MCP server brave-search!
Brave Search MCP Server running on stdio

	3.	When I attempted a web search in Claude Desktop using a natural language command like:
“Can you web search for the latest news on OpenAI today?”
The response returned:

Error: fetch failed

Steps to Reproduce

	1.	Add the Brave Search MCP Server configuration to claude_desktop_config.json.
	2.	Start Claude Desktop and verify the server is running and connected.
	3.	Use the web search tool (e.g., brave_web_search) with a query like:

{
  "query": "OpenAI latest news today",
  "count": 5
}

	4.	Observe the “fetch failed” error in the response.

Logs

Here is a snippet of the relevant logs:

Brave Search MCP Server running on stdio
2024-12-04T14:48:08.913Z [info] Connected to MCP server brave-search!
...
Error: fetch failed

Expected Behavior

The web search should return relevant results based on the query.

Questions

	1.	Is there a known issue with the Brave Search MCP Server, or am I misconfiguring something?
	2.	Are there additional steps required to validate the server setup?
	3.	How can I debug or get more detailed error information for the fetch failure?

Any guidance would be greatly appreciated!

**Comment by jspahrsummers** [comment]
Seems like the same issue as https://github.com/modelcontextprotocol/servers/issues/161?
