### ISSUE TITLE
github server: `merge_commit_sha`  should be nullable

### ISSUE THREAD

**Issue by sd2k** [modelcontextprotocol/servers#227]
It seems that the GitHub API will return `"merge_commit_sha": null` after creating a pull request, although I can't find that in the docs. When [parsing the response](https://github.com/modelcontextprotocol/servers/blob/94a36286d2ea49d095704167846283f0c2c2d5d1/src/github/index.ts#L242) `GitHubPullRequestSchema.parse` is failing with the following error:

```
Invalid arguments: merge_commit_sha: Expected string, received null
```

https://github.com/modelcontextprotocol/servers/blob/94a36286d2ea49d095704167846283f0c2c2d5d1/src/github/schemas.ts#L284

**Comment by msimism** [comment]
so I feel like my noob knowledge is going to show but I've noticed possible fixes in this ^ and afew other issues, I'm assuming they would have to get approved until their in the main version? is it possbiel to install these updates? ( at my own risk of course )
