### ISSUE TITLE
GitHub - Validation Error: Missing or Incorrectly Formatted content Field 

### ISSUE THREAD

**Issue by dancomanlive** [modelcontextprotocol/servers#244]
**Describe the bug**  
When connecting to the GitHub remote server to use any of the tools available, the response is missing the expected `content` field. The client fails with a validation error indicating that the `content` field is required and should be an array, but it is either undefined or incorrectly formatted.

**To Reproduce**  
1. Use the `client.callTool()` method to create a new issue on GitHub via the remote server.
2. Wait for the response from the remote server.

**Expected behavior**  
The expected behavior is that the remote server should return a properly structured response, including the `content` field, which should be an array containing information about the created issue.

**Logs**  
```
Error: {
  "issues": [
    {
      "code": "invalid_type",
      "expected": "array",
      "received": "undefined",
      "path": [
        "content"
      ],
      "message": "Required"
    }
  ],
  "name": "ZodError"
}
```

**Additional context**  
- The issue does not occur when connecting to a local server, which behaves as expected.
- The error happens only when interacting with the remote server.
- The client is using the same request parameters for both the local and remote servers, and the local server returns the expected response.

**Code to reproduce the issue:**

```javascript
// Get the absolute path to node
const nodePath = execSync("which node").toString().trim();

// Absolute path to local server script
const localServerPath = path.resolve(
  "/Users/me/Workspace/servers/src/github/dist/index.js" // Replace with the actual path to your local server entry point
);

// Remote server path
const remoteServerPath = ["-y", "@modelcontextprotocol/server-github"];

// Create a transport that connects to the server using stdio
const transport = new StdioClientTransport({
  command: npxPath,
  args: remoteServerPath,
  env: {
    GITHUB_PERSONAL_ACCESS_TOKEN: process.env.GITHUB_PERSONAL_ACCESS_TOKEN,
    PATH: `${process.env.PATH}:${nodePath}`,
  },
});
```

**Comment by jspahrsummers** [comment]
Seems like the same issue as https://github.com/modelcontextprotocol/servers/issues/165.

**Comment by dancomanlive** [comment]
> Seems like the same issue as #165.

Possibly. We can't do anything to fix this error on our side though.
