### ISSUE TITLE
"fetch is undefined" with slack mcp

### ISSUE THREAD

**Issue by HudZah** [modelcontextprotocol/servers#258]
**Describe the bug**
I receive an error called "fetch is undefined" when I try and use the Slack MCP after setting everything up correctly with a bot.

**To Reproduce**
1. Setup bot with the correct perms
<img width="663" alt="image" src="https://github.com/user-attachments/assets/9213a453-cf6c-4b88-a6b8-871577570645">

2. Add Slack to mcp config file with correct bot token and team id
<img width="587" alt="image" src="https://github.com/user-attachments/assets/5cef3458-ae60-4504-abdf-1f6f359d7617">
3. Try querying and it doesn't work

**Expected behavior**
I expected to be able to query my Slack and send messages and reactions, based on whatever permissions it has, but instead I just keep getting this error. 
<img width="716" alt="image" src="https://github.com/user-attachments/assets/ebfa1315-56a9-41a9-9fa7-3b6fe5b19c9a">

**Logs**
If applicable, add logs to help explain your problem.

**Additional context**

**Comment by stefandeml** [comment]
I have the same issue with the brave server. The Claude Desktop environment seems to be using a Node version that doesn't include `fetch` (pre-v18).
I'm using nix with the Node version explicitly pinned in the configuration:
```
   "brave-search": {
      "command": "/etc/profiles/per-user/foo/bin/npx",
      "args": [
        "-y  node@latest",
        "@modelcontextprotocol/server-brave-search"
      ],
      "env": {
        "BRAVE_API_KEY": "X"
      }
```

My node version is pinned to v20, which definitely includes `fetch`. Not clear where an older version could be leaking into the environment.

**Comment by jspahrsummers** [comment]
@HudZah It sounds like you're picking up an older version of Node. If you explicitly provide a path to a version of Node ≥ 18, it should work.

@stefandeml This argument from your configuration:
```
"-y  node@latest"
```
… will provide a _single_ argument with that value on the command line. Try separating it out into two strings.

**Comment by pirate-matt** [comment]
I got the same "fetch is undefined" issue, but with a different MCP. Tested a bunch of different things including:

```
"-y  node@latest"
```

For others still struggling, what finally worked was setting the path directly in "env":

```json
{
  "mcpServers": {
    "brave-search": {
      "command": "npx",
      "args": [
        "-y",
        "@modelcontextprotocol/server-brave-search"
      ],
      "env": {
        "BRAVE_API_KEY": "redacted",
        "PATH": "/Users/username/.nvm/versions/node/v20.8.0/bin:/usr/local/bin:/usr/bin:/bin"
      }
    }
  }
}
```

For those still debugging checking for specific errors with `tail` helped a lot:

```bash
tail -f ~/Library/Logs/Claude/mcp.log
```

**Comment by HudZah** [comment]
thank you! Pinning the path directly in Env worked
