### ISSUE TITLE
[RFC] Improve pull request creation with better validation and error handling

### ISSUE THREAD

**Issue by ivarvd-hldng** [modelcontextprotocol/servers#261]
Since I'm currently unable to create a pull request through the MCP server (which ironically demonstrates the issue I'm trying to fix), I'm submitting this as an RFC (Request for Comments) first.

## Proposed Changes
I have implemented the following improvements in my fork (ivarvd-hldng:fix/improve-pr-creation):

1. Added branch validation
2. Added commit difference checking
3. Enhanced error handling
4. Improved debugging capabilities

Full implementation details and testing steps are available in my fork at: https://github.com/ivarvd-hldng/servers/tree/fix/improve-pr-creation

Would you be interested in this improvement? If so, I can submit the PR through the GitHub web interface or we can discuss the best way to proceed.

## Background
This addresses the issue described in #259 where users encounter unhelpful \"Unprocessable Entity\" errors when creating pull requests.

## Implementation Details
```typescript
async function validateBranch(owner: string, repo: string, branch: string): Promise<boolean> {
  // Verify branch exists
}

async function getCommitDifference(
  owner: string,
  repo: string,
  base: string,
  head: string
): Promise<{ ahead_by: number; behind_by: number }> {
  // Check for mergeable changes
}

async function createPullRequest(...) {
  // 1. Validate branches
  // 2. Check commit differences
  // 3. Create PR with better error handling
}
```

Would appreciate your thoughts on this approach.

**Comment by jspahrsummers** [comment]
Please submit suggested changes via PRs instead of issues.
