### ISSUE TITLE
Node based Git Server

### ISSUE THREAD

**Issue by JonasHelming** [modelcontextprotocol/servers#271]
**Is your feature request related to a problem? Please describe.**
The current Git server is implemented in Python, which requires complicated set-up to run and manual download.
All other servers seem to be implemented based on Node, which is very conveniant.

**Describe the solution you'd like**
Switch to Node :-)

**Additional context**
Thank you for MCP and the available servers, really great initiative!

**Comment by jspahrsummers** [comment]
Thanks for the feedback! We're purposely demonstrating the use of different languages to build MCP servers in this repo. As these are meant as examples and reference implementations, we'd like to keep it as-is.
