### ISSUE TITLE
edit_file operation available in codebase but not exposed in MCP function set

### ISSUE THREAD

**Issue by kestervanleeuwen** [modelcontextprotocol/servers#324]
At first glance, the edit_file operation appears to be fully implemented in the server codebase (index.ts) with comprehensive functionality including:

Line-based and multi-line content matching
Whitespace normalization with indentation preservation
Multiple simultaneous edits with correct positioning
Git-style diff output
Dry run mode for previewing changes
Full implementation in both ListToolsRequestSchema and CallToolRequestSchema handlers
Complete EditFileArgsSchema definition and applyFileEdits function

However, when accessing the filesystem MCP server through the standard configuration:
jsonCopy"filesystem": {
  "command": "npx",
  "args": [
    "-y",
    "@modelcontextprotocol/server-filesystem",
    "<allowed-directories...>"
  ]
}

This appears to be a discrepancy between the implemented functionality and what's exposed to MCP clients. Could this be a versioning issue or is there additional configuration needed to enable this operation? Or am I missing something else?

**Comment by Aschent89** [comment]
Being discussed here: https://github.com/modelcontextprotocol/servers/issues/294
