### ISSUE TITLE
Is anyone working on file search support?

### ISSUE THREAD

**Issue by tim-carbonfarm** [modelcontextprotocol/servers#335]
**Is your feature request related to a problem? Please describe.**
The filesystem server works well but can only list and read entire files. For software development, a frequent need is to search for text (e.g. to find usages of a function across multiple files). To some extent an LLM can list and read all files with the filesystem server, but for large projects this is obviously limiting.

**Describe the solution you'd like**
A new MCP server for file search, either with exact matching or fuzzy search capabilities. Alternatively, a new functionality added to the filesystem server.

The ability to seek within files would also be quite powerful, e.g. to pull out snippets of code from large files without hitting context window limits.

**Describe alternatives you've considered**
This seems simple enough that I would consider implementing this myself but wanted to see if anyone else is already working on it, or if this functionality exists already in some tool that I'm not aware of.

**Comment by jspahrsummers** [comment]
[We aren't planning to add more servers](https://github.com/orgs/modelcontextprotocol/discussions/61) to this repo. Perhaps you'd like to [open a discussion](https://github.com/orgs/modelcontextprotocol/discussions) with the community—that'll give your question more visibility for other folks to answer.
