### ISSUE TITLE
Prerequisites are inadequate

### ISSUE THREAD

**Issue by gerrywastaken** [modelcontextprotocol/servers#35]
![Screenshot from 2024-11-25 20-06-20](https://github.com/user-attachments/assets/08b869ad-a736-4692-8da1-51fa05e2eb7f)

Apparently, you don't support Linux, but many people who build things and like to automate (your target audience) use that as their platform. Are you planning on releasing a Linux version?

Given that it is an Electron App, I would have thought releasing it to Linux would be the default. Or am I the only Linux Anthropic customer? :(

**Comment by jspahrsummers** [comment]
Sorry, this repository isn't for discussing Anthropic's product roadmap. I'd encourage you to share that feedback through other channels.

Note that MCP itself is definitely cross-platform, though.

**Comment by gerrywastaken** [comment]
Thanks @jspahrsummers. That is cool.

Side note now that I've started to develop MCP stuff. Most people are introduced to the usefulness of MCP via the desktop app. So no app, no understanding of MCP is even useful. The Claude desktop app is the gateway.
