### ISSUE TITLE
Security issues

### ISSUE THREAD

**Issue by polRk** [modelcontextprotocol/servers#54]
Now, scripts that run through nodejs/python can harm the user's computer or give more rights than this MCP server needs. 

The suggestion is to consider using Deno in the examples and explicitly specify the minimum permissions that are required for the MCP server

**Comment by jspahrsummers** [comment]
This would require adding (or verifying) Deno support in the TypeScript SDK. Would be happy to review that if you wanted to submit a PR! 🙏

**Comment by polRk** [comment]
@jspahrsummers If we take the launch via Dyno run (https://docs.deno.com/runtime/reference/cli/run /), then we must specify the path of the file or a link to the file (it is very convenient to use gist). But it is better to additionally publish the sdk in jsr (but it seems to work without it via @jsr/modelcontextprotocol__sdk)

**Comment by jspahrsummers** [comment]
Sorry, I'm not sure what the suggestion is here. Please feel free to submit a PR if there's something you think should change in the repo!
