### ISSUE TITLE
slack_search_messages isn't found

### ISSUE THREAD

**Issue by bartender911** [modelcontextprotocol/servers#61]
I apologize, but I don't see a slack_search_messages function in the available function list. The closest available Slack-related functions are:

slack_get_channel_history - Gets recent messages from a channel
slack_get_thread_replies - Gets all replies in a thread
slack_list_channels - Lists public channels
slack_post_message - Posts messages
slack_reply_to_thread - Replies to threads
slack_add_reaction - Adds reactions
slack_get_users - Lists users
slack_get_user_profile - Gets user profiles

**Comment by bartender911** [comment]
It seems that slack_search_messages was removed last week. Hopefully, it can be added back again soon.
https://github.com/modelcontextprotocol/servers/commit/93d0ce389c7af04e4307ed7ac4edea54e887813b

**Comment by dsp-ant** [comment]
We removed search_messages since it requires a user token and we want the server to work with a bot token. I have a PR up to fix the README.
