### ISSUE TITLE
Provide default permissions for a given server in the `config`

### ISSUE THREAD

**Issue by amirrezapanahi** [modelcontextprotocol/servers#68]
Firstly, this work is really exciting. Huge props to the developers behind all of this. 

I wonder if we can add default permissions to the `claude_desktop_config.json` file, specifying which tools we want to give default access to so that we are not asked repeatedly during chats with claude if we would like to provide access. I find that experience quite distracting.

<img width="768" alt="Screenshot 2024-11-26 at 21 39 43" src="https://github.com/user-attachments/assets/9d76669e-7b90-4bfe-83a1-550460073ef9">

If that has security implications as shown - can we instead specify which tools we would like to use by default. For example in the case of the `filesystem` we could specify in the config that we only want to use the tools `read_file`, `search_files` **only**

```
{
  "mcpServers": {
    "filesystem": {
      "command": "npx",
      "args": ["-y", "@modelcontextprotocol/server-filesystem", "/Users/YOUR_USERNAME/Desktop"],
      "tools": ["read_file", "search_files"]
    }
  }
}
```

Also, are there are any reference docs on the structure of `claude_desktop_config.json`?

**Comment by dsp-ant** [comment]
I agree, the current implementation can cause friction. The initial version leaned on the safe side. We are thinking of ways how to improve this.

**Comment by amirrezapanahi** [comment]
I'd be willing to help out if need be

**Comment by jspahrsummers** [comment]
Thanks for the feedback! I'm going to close this issue out, as this is about Claude Desktop and not the MCP example servers themselves.
