### ISSUE TITLE
Couldn't connect to MCP server slack

### ISSUE THREAD

**Issue by vit-personal** [modelcontextprotocol/servers#82]
Hi, I am trying to configure Slack integration.

Double-checked all troubleshooting steps:
✅ All required scopes are added to 
<img width="639" alt="Screenshot 2024-11-27 at 1 22 12 PM" src="https://github.com/user-attachments/assets/4ffecd2b-70f8-4c4c-b1f5-bb3e93465cf3">
my Slack app

✅ The app is properly installed on my workspace
<img width="719" alt="Screenshot 2024-11-27 at 1 22 33 PM" src="https://github.com/user-attachments/assets/23c5ebe8-729b-4f5c-9631-867764225bca">

✅ The tokens and workspace ID are correctly copied to your configuration
<img width="719" alt="Screenshot 2024-11-27 at 1 14 30 PM" src="https://github.com/user-attachments/assets/75fa8168-04a9-4077-956c-f11d9b3dda33">

✅ The app has been added to the channels it needs to access
<img width="337" alt="Screenshot 2024-11-27 at 1 23 49 PM" src="https://github.com/user-attachments/assets/a6653472-bcef-40d9-8dbd-30b707d142a4">

But when I launch Claude, I see an error 'Couldn't connect to MCP server slack'

Are there any other troubleshooting options?

**Comment by jspahrsummers** [comment]
Sorry, this is probably the same issue as https://github.com/modelcontextprotocol/servers/issues/40. We're working on a fix. 🙏

**Comment by vit-personal** [comment]
Not it works, it appeared that I didn't have `node` installed on my machine.
