### ISSUE TITLE
Custom Serve geting , Could not connect to MCP 

### ISSUE THREAD

**Issue by dominicdev** [modelcontextprotocol/servers#84]
I'm trying to create custom services using DDG, but getting error in claude desktop
im working in windows 

Already installed the dependencies

here is my code, this was from weather example from the doc but change the ddg 

`
import os
import json
import logging
from collections.abc import Sequence
from typing import Any

import httpx
import asyncio
from dotenv import load_dotenv
from mcp.server import Server
from mcp.types import (
    Resource,
    Tool,
    TextContent,
    ImageContent,
    EmbeddedResource
)
from pydantic import AnyUrl
from duckduckgo_search import AsyncDDGS
# Load environment variables
load_dotenv()

# Configure logging
logging.basicConfig(level=logging.INFO)

logger = logging.getLogger("duckduckgo_service")

async def aget_results(word):
    results = await AsyncDDGS(proxy=None).atext(word, max_results=10)
    return results

async def fetch_ddg(search: str) -> dict[str, Any]:
    words = [search]
    tasks = [aget_results(w) for w in words]
    results = await asyncio.gather(*tasks)
    return  results 

app = Server("duckduckgo_service")

@app.list_resources()
async def list_resources() -> list[Resource]:
    """List available weather resources."""
    uri = AnyUrl(f"ddg://search/current")
    return [
        Resource(
            uri=uri,
            name=f"Current ddg in search",
            mimeType="application/json",
            description="Latest search data"
        )
    ]

@app.read_resource()
async def read_resource(uri: AnyUrl) -> str:
    """Read current ddg data for a search."""
    
    if str(uri).startswith("ddg://") and str(uri).endswith("/current"):
        search = str(uri).split("/")[-2]
    else:
        raise ValueError(f"Unknown resource: {uri}")

    try:
        search_data = await fetch_ddg(search)
        return json.dumps(search_data, indent=2)
    except httpx.HTTPError as e:
        raise RuntimeError(f"DDG API error: {str(e)}")

@app.list_tools()
async def list_tools() -> list[Tool]:
    """List available search tools."""
    return [
        Tool(
            name="get-ddg",
            description="Get DDG Search for a user query",
            inputSchema={
                "type": "object",
                "properties": {
                    "search": {
                        "type": "string",
                        "description": "search query"
                    }, 
                },
                "required": ["search"]
            }
        )
    ]

@app.call_tool()
async def call_tool(name: str, arguments: Any) -> Sequence[TextContent | ImageContent | EmbeddedResource]:
    """Handle tool calls for ddg search."""
    if name != "get-ddg":
        raise ValueError(f"Unknown tool: {name}")

    if not isinstance(arguments, dict) or "search" not in arguments:
        raise ValueError("Invalid forecast arguments")

    search = arguments["search"] 

    try:
        words = [search]
        tasks = [aget_results(w) for w in words]
        results = await asyncio.gather(*tasks)
    # return  results 

        return [
            TextContent(
                type="text",
                text=json.dumps(results, indent=2)
            )
        ]
    except httpx.HTTPError as e:
        logger.error(f"DDG API error: {str(e)}")
        raise RuntimeError(f"DDG API error: {str(e)}")

async def main():
    # Import here to avoid issues with event loops
    from mcp.server.stdio import stdio_server

    async with stdio_server() as (read_stream, write_stream):
        await app.run(
            read_stream,
            write_stream,
            app.create_initialization_options()
        )
`
also where I can see the log for MCP?

here is the config 

`
{
  "mcpServers": {
    "filesystem": {
      "command": "C:\\Program Files\\nodejs\\node.exe",
      "args": [
        "C:\\Users\\Admin\\AppData\\Roaming\\npm\\node_modules\\@modelcontextprotocol\\server-filesystem\\dist\\index.js",
        "D:\\Documents\\work\\MCP"
      ]
    },
    "duckduckgo_service": {
      "command": "C:\\ProgramData\\chocolatey\\bin\\uvx.exe",
      "args": [
        "--directory",
        "C:\\Users\\Admin\\duckduckgo_service",
        "run",
        "duckduckgo_service"
      ]
    }
  }
}
`

**Comment by jspahrsummers** [comment]
Sorry, it's hard to understand the issue you're reporting here, as the body isn't formatted for readability. Please try out our [debugging guide](https://modelcontextprotocol.io/docs/tools/debugging), and if you still have issues, please open a new issue describing the exact issue and error logs you're seeing.
