### ISSUE TITLE
Should we also have a Confluence Docs MCP Server?

### ISSUE THREAD

**Issue by jasbir98** [modelcontextprotocol/servers#90]
I built something for my company internally which helped query confluent data through an LLM running locally. It helped a lot to find answers hidden in those confluent pages. Will it be useful here as well? I would love to contribute 🙂

**Comment by dsp-ant** [comment]
We welcome any new server additions. Feel free to work on one and send a link by opening a PR with changes to README.md such as https://github.com/modelcontextprotocol/servers/commit/4dacf51240db90adbc89c94d2228918a6a3992a2
