### ISSUE TITLE
Is it possible to add a prompt or few-shot examples for the servers to use?

### ISSUE THREAD

**Issue by sengland-4way** [modelcontextprotocol/servers#97]
Is it currently possible to add prompting and/or few shot examples to guide the tools, this would expedite to process of finding the correct data or displaying it in the correct format, particularly useful for the Postgres server. We could provide shortcuts instead of the LLM figuring out which tables are relevant and we can guide the LLM when tables/statuses are not immediately obvious.

If it is not possible, then I guess I am opening up a feature request, it would make sense to have under the development/MCP area of the UI a place to enter tool descriptions, prompts of few shot examples.

**Comment by jspahrsummers** [comment]
MCP tools support providing a description, where these examples can be provided.

Closing this out, as it's not specifically related to the example servers. Please feel free to [open a discussion](https://github.com/orgs/modelcontextprotocol/discussions) if you have other questions.
