### ISSUE TITLE
Questions on MCP's intended usage patterns

### ISSUE THREAD

**Issue by ferrants** [modelcontextprotocol/servers#99]
**Is your feature request related to a problem? Please describe.**
No problem, just some questions on intended usage patterns

**Describe the solution you'd like**
No solution suggestion, just some questions

**Describe alternatives you've considered**
I've read through the docs and have set up a Python server to explore

**Additional context**

Love the initiative, glad to see attempts of standardization. Some questions:

Are there any clients that exist besides Claude Desktop? Plans for any? Any repos implementing the client side?

Seemingly Claude Desktop doesn't work on Linux, is there a good way to validate behavior if developing on Linux?

The MCP Server is meant to run locally, installed by the user, not run somewhere in the cloud? How do you envision people who aren't technical to configure this? Model "Store" coming in the future?

**Comment by dsp-ant** [comment]
For Linux, the best approach is using the inspector `npx @modelcontextprotocol/inspector`. There is cody and zed as clients with some restrictions. See the manual: https://modelcontextprotocol.io/clients

There are early thinkings on making servers remote capable, as a cloud service. 

This feels more like a discussion and not an issue. If you have further questions please create a topic in the discussion forums
